import 'package:flutter/material.dart';
import 'package:instant_pay_u/services/utilities/image_constant.dart';

class DummyDb {
  final List<Map> onboardingData = [
    {
      "title": "Welcome to MyApp",
      "description": "Discover new ways to achieve your goals with our app.",
      "image": ImageConstant.ONBOARDINGIMAGE1,
    },
    {
      "title": "Track Your Progress",
      "description": "Stay on top of your tasks and achieve more every day.",
      "image": ImageConstant.ONBOARDINGIMAGE2,
    },
    {
      "title": "Achieve Your Goals",
      "description":
          "With our tools, reaching your goals has never been easier.",
      "image": ImageConstant.ONBOARDINGIMAGE3,
    },
  ];
  final List<Map> transferMethode = [
    {"title": "Pay to \nContact", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
    {"title": "", "icon": Icons.person},
  ];
}
